name: Generate Python Client

on:
  push:
    branches:
      - main
    paths:
      - "user-service-api/**"
  workflow_dispatch:

jobs:
  generate-client:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the bundled OpenAPI specification
      - name: Download bundled OpenAPI specification
        run: |
          curl -o bundled-user-service.json "https://api.stoplight.io/projects/cHJqOjI2NzEyNA/branches/main/export/user-service-api/user-service.json"
          ls -la

      # Step 2: Set up Java for openapi-generator
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Install openapi-generator-cli
      - name: Install openapi-generator-cli
        run: |
          curl -L https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.10.0/openapi-generator-cli-7.10.0.jar -o openapi-generator-cli.jar

      # Step 4: Clone the python-user-service-client repository
      - name: Clone python-user-service-client
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.CODE_GENERATION_PAT }}@github.com/overparser/python-user-service-client.git python-user-service-client
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      # Step 5: Generate Python client code directly into the client repository
      - name: Generate Python client code
        run: |
          java -jar openapi-generator-cli.jar generate \
            -i bundled-user-service.json \
            -g python-pydantic-v1 \
            -o python-user-service-client \
            --library asyncio

      # Step 6: Commit and push changes
      - name: Commit and push changes
        run: |
          cd python-user-service-client
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update Python client from user-service-api"
          git push origin HEAD:update-user-service-api --force

      # Step 7: Install GitHub CLI and create a Pull Request
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Pull Request
        run: |
          cd python-user-service-client
          echo "${{ secrets.CODE_GENERATION_PAT }}" | gh auth login --with-token
          gh pr create --repo overparser/python-user-service-client \
            --base main \
            --head update-user-service-api \
            --title "Update Python client from user-service-api" \
            --body "This PR updates the Python client based on the latest API specification."
